Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine39"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"

    vb.customize [
        'modifyvm', :id,
        '--nic1', 'intnet',
        '--intnet1', 'pxe_network',
        '--boot1', 'net',
        '--boot2', 'none',
        '--boot3', 'none',
        '--boot4', 'none'
      ]
  end
end
