dhcpd:
  device: eth1
  subnets:
    - netmask: 255.255.255.0
      network: 192.168.33.0
      nextServer: 192.168.33.10
      filename: undionly.kpxe
      range:
        start: 192.168.33.100
        end: 192.168.33.200
